In [2]:
import pandas as pd

df = pd.read_csv('Dataset 2.csv')

df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [3]:
print("Rows =", df.shape[0])
print("Columns =", df.shape[1])

Rows = 750
Columns = 10

In [4]:
print(df.columns)

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [5]:
numerical = df.select_dtypes(include=['int64','float64']).columns
categorical = df.select_dtypes(include=['object']).columns

print("Numerical Features:")
print(numerical)

print("\nCategorical Features:")
print(categorical)

Numerical Features:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Features:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

In [6]:
print(df.isnull().sum())

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

In [7]:
avg_age = df['Age'].mean()

print("Average Age =", avg_age)

Average Age = 41.824

In [8]:
avg_watch = df['WatchHoursPerWeek'].mean()

print("Average Watch Hours =", avg_watch)

Average Watch Hours = 14.236

In [9]:
avg_spend = df['MonthlySpend'].mean()

print("Average Monthly Spending =", avg_spend)

Average Monthly Spending = 689.9053333333334

In [10]:
print(df['SubscriptionType'].value_counts())

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

In [11]:
renewed_percentage = (
    df['SubscriptionRenewed']
    .value_counts(normalize=True)['Yes']
) * 100

print("Renewal Percentage =", renewed_percentage)

Renewal Percentage = 46.266666666666666

In [12]:
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

encoder = LabelEncoder()

for col in ['Gender',
            'SubscriptionType',
            'FavoriteGenre',
            'SubscriptionRenewed']:

    df_encoded[col] = encoder.fit_transform(df_encoded[col])

df_encoded.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

In [13]:
X = df_encoded.drop(
    ['UserID','SubscriptionRenewed'],
    axis=1
)

y = df_encoded['SubscriptionRenewed']

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [15]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [16]:
from sklearn.metrics import accuracy_score

y_pred_dt = dt.predict(X_test)

dt_accuracy = accuracy_score(
    y_test,
    y_pred_dt
)

print("Accuracy =", dt_accuracy)

Accuracy = 0.56

In [17]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    y_pred_dt
)

print(cm)

[[48 34]
 [32 36]]

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn = KNeighborsClassifier(
    n_neighbors=5
)

knn.fit(
    X_train_scaled,
    y_train
)

KNeighborsClassifier()

In [19]:
y_pred_knn = knn.predict(
    X_test_scaled
)

knn_accuracy = accuracy_score(
    y_test,
    y_pred_knn
)

print("Decision Tree =", dt_accuracy)
print("KNN =", knn_accuracy)

Decision Tree = 0.56
KNN = 0.54

In [20]:
from sklearn.linear_model import LinearRegression

X_reg = df_encoded.drop(
    ['UserID','MonthlySpend'],
    axis=1
)

y_reg = df_encoded['MonthlySpend']

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.20,
    random_state=42
)

lr = LinearRegression()

lr.fit(
    X_train_reg,
    y_train_reg
)

LinearRegression()

In [21]:
new_user = [[
    25,
    1,
    2,
    15,
    3,
    1,
    20,
    1
]]

prediction = lr.predict(
    new_user
)

print(
    "Predicted Monthly Spend =",
    prediction[0]
)

Predicted Monthly Spend = 1320.4204054466065

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(